# Generated by Django 4.2.30 on 2026-05-03 06:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0009_quiz_student_answer'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='assignment',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterModelOptions(
            name='topic',
            options={'ordering': ['order', '-date', '-created_at']},
        ),
        migrations.AlterField(
            model_name='activitylog',
            name='action',
            field=models.CharField(choices=[('login', 'User Login'), ('logout', 'User Logout'), ('quiz_attempt', 'Quiz Attempted'), ('assignment_sub', 'Assignment Submitted'), ('topic_done', 'Topic Completed'), ('contact_msg', 'Contact Message Sent'), ('ai_quiz_gen', 'AI Quiz Generated'), ('chat_message', 'Chatbot Message'), ('course_select', 'Course Selected'), ('user_approved', 'User Approved')], max_length=30),
        ),
        migrations.AlterField(
            model_name='assignment',
            name='course',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assignments', to='portal.course'),
        ),
        migrations.AlterField(
            model_name='chatmessage',
            name='topic',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='clientproject',
            name='demo_video_url',
            field=models.URLField(blank=True),
        ),
        migrations.AlterField(
            model_name='clientproject',
            name='live_url',
            field=models.URLField(blank=True),
        ),
        migrations.AlterField(
            model_name='clientproject',
            name='progress',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='clientproject',
            name='tech_stack',
            field=models.CharField(blank=True, max_length=300),
        ),
        migrations.AlterField(
            model_name='course',
            name='duration',
            field=models.CharField(blank=True, max_length=60),
        ),
        migrations.AlterField(
            model_name='course',
            name='icon',
            field=models.CharField(blank=True, default='school', max_length=60),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='registration_course',
            field=models.ForeignKey(blank=True, help_text='Course selected during registration. Auto-enrolled on admin approval.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='registered_students', to='portal.course'),
        ),
        migrations.AlterField(
            model_name='demoschedule',
            name='video_url',
            field=models.URLField(blank=True),
        ),
        migrations.AlterField(
            model_name='note',
            name='course',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='notes', to='portal.course'),
        ),
        migrations.AlterField(
            model_name='notification',
            name='target_role',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='quiz',
            name='course',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='quizzes', to='portal.course'),
        ),
        migrations.AlterField(
            model_name='userquery',
            name='answer',
            field=models.TextField(blank=True),
        ),
    ]
